name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian_version: [bullseye, bookworm]
    container:
      image: debian:${{ matrix.debian_version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        apt update && apt -y install cmake build-essential pkg-config libssl-dev python3-protobuf protobuf-compiler-grpc libgrpc++-dev && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && make install
      working-directory: ./kuka-external-control-sdk/build
