name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora_version: [38, 39]
    container:
      image: fedora:${{ matrix.fedora_version }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        dnf -y install cmake gcc-c++ python3-protobuf protobuf-compiler protobuf-devel grpc-cpp grpc-devel openssl openssl-devel && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && make install
      working-directory: ./kuka-external-control-sdk/build
