name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.9

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        yum install -y https://extras.getpagespeed.com/release-latest.rpm && yum install -y cmake gcc-c++ python3-protobuf protobuf-compiler protobuf-devel openssl openssl-devel && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && sudo make install
      working-directory: ./kuka-external-control-sdk/build
