name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: almalinux:8

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        dnf install -y https://repo.almalinux.org/almalinux/almalinux-release-synergy-latest-8.noarch.rpm && dnf --enablerepo=powertools install -y cmake gcc-c++ python3-protobuf protobuf-compiler protobuf-devel openssl openssl-devel grpc-devel && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && sudo make install
      working-directory: ./kuka-external-control-sdk/build
