name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rhel_version: [8, 9]
      fail-fast: false
    container:
      image: almalinux:${{ matrix.rhel_version }}

    steps:
    - uses: actions/checkout@v2


    - name: Install protobuf for RHEL 8
      if: matrix.rhel_version == 8
      run: dnf --enablerepo=powertools install protobuf-devel
    - name: Install protobuf for RHEL 9
      if: matrix.rhel_version == 9
      run: dnf --enablerepo=crb install protobuf-devel
    - name: Install dependencies
      run: |
        #!/bin/bash
        dnf install -y https://repo.almalinux.org/almalinux/almalinux-release-synergy-latest-${{ matrix.rhel_version }}.noarch.rpm && dnf install -y cmake gcc-c++ python3-protobuf protobuf-compiler openssl openssl-devel grpc-devel grpc-plugins && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && make install
      working-directory: ./kuka-external-control-sdk/build
