name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        #!/bin/bash
        apt update && apt -y install cmake build-essential pkg-config libssl-dev python3-protobuf protobuf-compiler-grpc libgrpc++-dev nanopb libnanopb-dev && cd kuka-external-control-sdk && mkdir build

    - name: Build and install
      run: cmake .. && make install
      working-directory: ./kuka-external-control-sdk/build
